version: '3'
services:
  nuxt-app:
    platform: linux/amd64
    image: node:latest
    container_name: nuxt-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: "sh -c 'npm install && npm run dev'"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000

networks:
  default:
    driver: bridge
